# Generated by Django 5.0 on 2025-06-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('1', 'Chat'), ('2', 'Video')], max_length=255),
        ),
    ]
